places = ['New Zealand', 'Japan', 'Grand Canyon', 'Hawaii', 'France']
print(places)
print(sorted(places))
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
